FORMAT: 1A
HOST: https://obscure-stream-80481.herokuapp.com

# zappo

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/teams]

### TEAMS [GET]

+ Response 200 (application/json)

        {
            "teams": [
                "id": 0,
                "name":"string",
                "is_still_in": boolean
            ]
        }

### ADD_TEAM [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "name": "string",
            "is_still_in": boolean
        }


+ Response 200(application/json)

    + Headers

            Location: /check

    + Body
    
            { 
                "id": 0,
                "name":"string",
                "is_still_in": boolean
            }
            
### EDIT_TEAM [PUT]

+ Request(application/json)

        {
            "id": 0,
            "name":"string",
            "is_still_in": boolean
        }

+ Response 200(application/json)

        {
            "id": 0,
            "name":"string",
            "is_still_in": boolean
        }